// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx8cgrzJ0cUU3Gc_DBI4-lKiR-N1MVPCY',
    appId: '1:122960985991:web:558c820fba9c0349559d22',
    messagingSenderId: '122960985991',
    projectId: 'achuar-translator',
    authDomain: 'achuar-translator.firebaseapp.com',
    storageBucket: 'achuar-translator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4o2Si9GIsyEMZtg5DU_9G1JeYHgD-v-4',
    appId: '1:122960985991:android:e3a96be3a4c21b5f559d22',
    messagingSenderId: '122960985991',
    projectId: 'achuar-translator',
    storageBucket: 'achuar-translator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6en5pY9kPTk2zQPx2Q16mpuWP5z2o4k',
    appId: '1:122960985991:ios:e61a311cdf18ba43559d22',
    messagingSenderId: '122960985991',
    projectId: 'achuar-translator',
    storageBucket: 'achuar-translator.firebasestorage.app',
  );
}
